version: "2.1"

volumes:
  data:
  walletstore:

networks:
  mynetwork.com:
    external:
      name: network_testv1

services:
  explorerdb.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.com
    hostname: explorerdb.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - mynetwork.com

  explorer.com:
    image: hyperledger/explorer:1.1.8
    container_name: explorer.com
    hostname: explorer.com
    environment:
      - DATABASE_HOST=explorerdb.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./organizations:/tmp/crypto
      - walletstore:/opt/wallet
      - ./organizations/:/etc/data
    ports:
      - 6060:6060
    depends_on:
      explorerdb.com:
        condition: service_healthy
    networks:
      - mynetwork.com
